/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pwdKavach.ui.additem;

import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javafx.scene.Parent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pwdKavach.database.DatabaseHandler;
import pwdKavach.main.MainFrame;
import pwdKavach.ui.login.LoginForm;

/**
 *
 * @author Administrator
 */
public class AddAccount extends javax.swing.JFrame {

    /**
     * Creates new form AddAccount
     */
    
    DatabaseHandler handler = null;
    
    public AddAccount() {
        handler = DatabaseHandler.getInstance();
        initComponents();
        loadComboBox("");   
        System.out.println(getGroupID());
//        MainFrame mf = new MainFrame();
//        String selectedValueFromList = mf.getSelectedValueOfList();
//        ComboBoxGroup.setSelectedItem(selectedValueFromList);
//        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddEntryTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblTitle1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();
        ComboBoxGroup = new javax.swing.JComboBox();
        lblPassword = new javax.swing.JLabel();
        lblPasswordConfirm = new javax.swing.JLabel();
        lblURL = new javax.swing.JLabel();
        lblGroup = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnGeneratePassword = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lblAddEntryTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAddEntryTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddEntryTitle.setText("Add Entry");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitle.setText("Title:");

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitle1.setText("Username:");

        ComboBoxGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword.setText("Password:");

        lblPasswordConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPasswordConfirm.setText("Repeat:");

        lblURL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblURL.setText("URL:");

        lblGroup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGroup.setText("Group:");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        btnGeneratePassword.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnGeneratePassword.setText("•••");
        btnGeneratePassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("C+V");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddEntryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addGap(18, 18, 18)
                                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPassword)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTitle1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPasswordConfirm)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblURL)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblGroup)
                                    .addGap(18, 18, 18)
                                    .addComponent(ComboBoxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnGeneratePassword)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAddEntryTitle)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(btnGeneratePassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordConfirm)
                    .addComponent(jButton1)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblURL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGroup))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //load combobox with default items
   public void loadComboBox(String groupname){
         //MainFrame mff = new MainFrame();
        //String groups[]={"Banking", "Social", "Office"};
        //ArrayList<String> groups = mff.getGroupListElements();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ComboBoxGroup.setModel(model);
        
      //ResultSet resultSet =  handler.getGroupResultSet(groupname);
        ResultSet resultSet =  handler.getGroupResultSet(groupname);

         if(resultSet == null)
        {
        JOptionPane.showMessageDialog(null, "An error occured no ResultSet, main.java", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
            try {
            
            System.out.println("loading List table");
            while(resultSet.next()){
                
                String groupN = resultSet.getString("groupname");
                System.out.println("inside resultset" + groupN);
                model.addElement(groupN);
               
            }
            
        } catch (SQLException e) {
            System.out.println("FillComboBox error" + e.getMessage());
        }
            finally // for elmininating database lock issue
       {
            try {
                resultSet.close();
                
            } catch (SQLException e) {
            }
        }
        
    }
    
   
    
    //Pass SelectedItem to MainFrame for assigning table value post close of this add form
   //Enter btnOKActionPerformed for guessing combox default value
    public String getSelectedItem() {
        return (String) ComboBoxGroup.getSelectedItem();
    }
    
    public int getSelectedIndex(){
        return ComboBoxGroup.getSelectedIndex();
    }
    
    
    public void inflateUI(String sItem){
        
        ComboBoxGroup.setSelectedItem(sItem);
    }
    
    //get group id specific to user
    private int getGroupID(){
        String groupName = ComboBoxGroup.getSelectedItem().toString();
        System.out.println("GroupName for searching id " + groupName);
        int id = handler.findGroupID(groupName);
        System.out.println("Group id is "+id);
        return id;
    }
    
    //Access OK button and change its text
    //private javax.swing.JButton btnOK;
    public void setbuttonOK(String text) {
     btnOK.setText(text);
     }
    
    //call add entry method
    private void addEntryActionPerform(){
      String title = txtTitle.getText();
      String username = txtUsername.getText();
      String password = String.valueOf(txtPassword.getPassword());
      String url = txtURL.getText();
      String groupValue = ComboBoxGroup.getSelectedItem().toString();
      
      
      if(groupValue == null){
          JOptionPane.showMessageDialog(null, "Please select group", "", JOptionPane.ERROR_MESSAGE);
          return;  // to close popup window
      }
        
      if(handler.insertIntoAccountsTable(LoginForm.getID(), getGroupID(), title, username, password, url, groupValue)){
          
          //this.dispose(); // dispose add entry window post addition of an item
          
          JOptionPane.showMessageDialog(null, "You have added the entry successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
          this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
          
      }
      else
      {
          JOptionPane.showMessageDialog(null, "Couldn't add an entry", "Error", JOptionPane.ERROR_MESSAGE);
          this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
      }
        
    }
    
    // Add Account button
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        
     if(btnOK.getText().equals("ADD")){
         addEntryActionPerform();
     }   
     else{
         JOptionPane.showMessageDialog(null, "Its not ADD", "",JOptionPane.ERROR_MESSAGE);
     }
      
    }//GEN-LAST:event_btnOKActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //this.setEnabled(true);
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxGroup;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGeneratePassword;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAddEntryTitle;
    private javax.swing.JLabel lblGroup;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordConfirm;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblURL;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
